line-length = 120
src = ["src", "."]
select = [
    "F", # Pyflakes
    "E", # Pycodestyle Error
    "W", # PycodeStyle Warning
    "I", # Isort
    "N", # pep8-naming
    "UP", # pyupgrade
    "YTT", # flake8-2020
    "B", # flake8-bugbear
    "C4", # flake8-comprehensions
    "DTZ", # flake8-datetimez
    "T10", # flake8-debugger
    "ISC", # flake8-implicit-str-concat
    "G", # flake8-logging-format
    "PIE", # flake8-pie
    "T20", # flake8-print
    "PYI", # flake8-pyi
    "Q", # flake8-quotes
    "RSE", # flake8-raise
    "RET", # flake8-return
    "SIM", # flake8-simplify
    "TID", # flake8-tidy-imports
    "PTH", # flake8-use-pathlib
    "TD", # flake8-todos
    "PGH", # pygrep-hooks
    "PL", # Pylint
    "TRY", # tryceratops
    "RUF",  # Ruff-specific rules
]
ignore = [
    "B005", # strip-with-multi-characters
    "B905", # zip-without-explicit-strict
    "N818", # error-suffix-on-exception-name
    "Q003", # avoidable-escaped-quote
    "SIM108", # if-else-block-instead-of-if-exp
    "SIM212", # if-expr-with-twisted-arms
    "PTH123", # builtin-open
    "TD002",  # missing-todo-author
    "PLR0911", # too-many-return-statements
    "PLR0912", # too-many-branches
    "PLR0913", # too-many-arguments
    "PLR0915", # too-many-statements
    "PLR2004", # magic-value-comparison
    "PLW2901", # redefined-loop-name
    "SIM300", # yoda-conditions
    "TID252", # relative-imports
    "PGH004", # blanket-noqa
    "TRY002", # raise-vanilla-class
    "TRY003", # raise-vanilla-args
    "TRY200", # reraise-no-cause
    "RUF001", # ambiguous-unicode-character-string
    "RUF002", # ambiguous-unicode-character-docstring
    "RUF003", # ambiguous-unicode-character-comment
    "RUF005", # collection-literal-concatenation
    "RUF006", # asyncio-dangling-task
    "RUF012", # mutable-class-default
    "RET504", # unnecessary-assign
]
target-version = "py310"

[per-file-ignores]
"tests*/**/*.py" = [
    "N", # pep8-naming
]

[isort]
combine-as-imports = true
no-lines-before = ["local-folder"]
